export const CITY_COORDINATES = {
  'New York, NY': { lat: 40.7128, lng: -74.006 },
  'Chicago, IL': { lat: 41.8781, lng: -87.6298 },
  'Los Angeles, CA': { lat: 34.0522, lng: -118.2437 },
  'Seattle, WA': { lat: 47.6062, lng: -122.3321 },
  'Atlanta, GA': { lat: 33.749, lng: -84.388 },
  'Miami, FL': { lat: 25.7617, lng: -80.1918 },
  'Cleveland, OH': { lat: 41.4993, lng: -81.6944 },
  'Detroit, MI': { lat: 42.3314, lng: -83.0458 },
  'Philadelphia, PA': { lat: 39.9526, lng: -75.1652 },
  'Boston, MA': { lat: 42.3601, lng: -71.0589 },
}

export const DEFAULT_AGENTS = [
  {
    id: 'planner',
    name: 'Planner Agent',
    role: 'Master Orchestrator',
    status: 'active',
    lastActivity: 'Breaking user goals into coordinated workflows.',
    description: 'Owns planning, delegation, and completion tracking for every user request.',
  },
  {
    id: 'risk-detection',
    name: 'Risk Detection Agent',
    role: 'Threat Analysis',
    status: 'active',
    lastActivity: 'Scanning shipment health, delays, and risk spikes.',
    description: 'Detects disruption signals, scores shipment risk, and raises action priorities.',
  },
  {
    id: 'supply-optimization',
    name: 'Supply Chain Optimizer',
    role: 'Route Planning',
    status: 'active',
    lastActivity: 'Optimizing routes, ETA confidence, and throughput.',
    description: 'Recommends better routes, speed adjustments, and operational tradeoffs.',
  },
  {
    id: 'crisis-response',
    name: 'Crisis Response Agent',
    role: 'Emergency Management',
    status: 'idle',
    lastActivity: 'Standing by for critical shipment incidents.',
    description: 'Handles urgent incidents, escalations, and contingency plans for blocked shipments.',
  },
  {
    id: 'communication',
    name: 'Communication Agent',
    role: 'Stakeholder Relations',
    status: 'active',
    lastActivity: 'Preparing concise updates for operators and customers.',
    description: 'Turns agent outputs into user-facing updates, alerts, and next-step guidance.',
  },
  {
    id: 'blockchain',
    name: 'Blockchain Logger',
    role: 'Immutable Audit',
    status: 'active',
    lastActivity: 'Recording significant supply-chain events for auditability.',
    description: 'Maintains an immutable-style activity log for payments, milestones, and incidents.',
  },
  {
    id: 'rag',
    name: 'RAG Context Agent',
    role: 'Knowledge Retrieval',
    status: 'active',
    lastActivity: 'Gathering route, weather, and policy context.',
    description: 'Provides operational context so other agents can respond with grounded recommendations.',
  },
  {
    id: 'executor',
    name: 'Executor Agent',
    role: 'Action Execution',
    status: 'active',
    lastActivity: 'Executing approved tasks and updating backend state.',
    description: 'Applies approved actions, updates records, and closes completed tasks.',
  },
]

export const DEFAULT_SHIPMENT_BLUEPRINTS = [
  {
    id: 'SHP-2024-001',
    name: 'Medical Supplies - Chicago',
    origin: 'New York, NY',
    destination: 'Chicago, IL',
    status: 'in-transit',
    riskScore: 32,
    riskLevel: 'low',
    progress: 67,
    lastUpdate: 'On schedule, no delays detected.',
    averageSpeed: 85,
  },
  {
    id: 'SHP-2024-002',
    name: 'Electronics - Seattle',
    origin: 'Los Angeles, CA',
    destination: 'Seattle, WA',
    status: 'delayed',
    riskScore: 68,
    riskLevel: 'medium',
    progress: 45,
    lastUpdate: 'Weather delay in Portland corridor.',
    averageSpeed: 65,
  },
  {
    id: 'SHP-2024-003',
    name: 'Perishable Goods - Miami',
    origin: 'Atlanta, GA',
    destination: 'Miami, FL',
    status: 'crisis',
    riskScore: 89,
    riskLevel: 'critical',
    progress: 58,
    lastUpdate: 'Cold-chain integrity alert triggered.',
    averageSpeed: 40,
  },
  {
    id: 'SHP-2024-004',
    name: 'Manufacturing Parts - Detroit',
    origin: 'Cleveland, OH',
    destination: 'Detroit, MI',
    status: 'in-transit',
    riskScore: 45,
    riskLevel: 'medium',
    progress: 72,
    lastUpdate: 'Minor traffic delays on I-75.',
    averageSpeed: 75,
  },
  {
    id: 'SHP-2024-005',
    name: 'Pharmaceuticals - Boston',
    origin: 'Philadelphia, PA',
    destination: 'Boston, MA',
    status: 'in-transit',
    riskScore: 28,
    riskLevel: 'low',
    progress: 81,
    lastUpdate: 'Ahead of schedule.',
    averageSpeed: 90,
  },
]
